Nächste KoMata und Timeline aktualisiert
Die-KoMa/die-koma.org pull request #141
Opened 2020-10-05 11:50 UTC by Grarie

2020-10-05 12:29 UTC, nicoa requested changes
@Grarie reviewed :-)

2020-10-05 12:29 UTC, nicoa commented on ueber_die_koma/timeline.md
> +| WS 2020/21  | KoMa 87                | Uni Bonn                   | SS 2021       |
steht das fest dass Bonn statt Dresden im SoSe stattfindet? oder ist das ein Zahlendreher?

2020-10-05 12:29 UTC, nicoa commented on _includes/next_koma.html
> +        <span class="name">KoMa 87 in Bonn</span>
s.u.: so richtig?

2020-10-05 12:29 UTC, nicoa commented on _includes/next_koma.html
> +        <span class="name"><a href="https://koma87.uni-jena.de/">KoMa 86 in Jena</a></span>
die Seite ist immer noch wahlweise die Standardseite des Providers (http) oder eine kaputte SSL-Verbindung (https) - wollt ihr das nicht lieber erstmal rauslassen und dann reinnehmen wenn es zumindest halb fertig ist?

2020-10-05 13:24 UTC, Grarie commented on ueber_die_koma/timeline.md
> +| WS 2020/21  | KoMa 87                | Uni Bonn                   | SS 2021       |
Jep, Bonn übernimmt für Dresden. Wurde Samstag von den beiden Fachschaften beschlossen.

2020-10-05 13:26 UTC, Grarie commented on _includes/next_koma.html
> +        <span class="name"><a href="https://koma87.uni-jena.de/">KoMa 86 in Jena</a></span>
Stimmt. Der Link war auch falsch (86 muss es sein).

Inhalt ist da dennoch nicht. Also rauslassen? Ich würde den Link eigentlich lieber behalten und auf die Website schreiben "hier entsteht die KoMa Seite für Jena". Was meinst du?

2020-10-05 13:30 UTC, Grarie commented on _includes/next_koma.html
> +        <span class="name"><a href="https://koma87.uni-jena.de/">KoMa 86 in Jena</a></span>
Okay, da ist was mit dem Rechenzentrum schief gelaufen. Die geht doch auch noch nicht. :(

2020-10-05 13:46 UTC, nicoa commented on _includes/next_koma.html
> +        <span class="name"><a href="https://koma87.uni-jena.de/">KoMa 86 in Jena</a></span>
wenn auf der webseite stehen würde dass da irgendwann was kommt wäre das fine. aber so haben wir eine nicht hilfreiche und eine nicht hilfreiche mit kpautten ssl :-P

2020-10-06 07:27 UTC, nicoa approved these changes

2020-10-06 07:27 UTC, merged