Kleinere Aktualisierungen
Die-KoMa/die-koma.org pull request #171
Opened 2022-11-01 00:46 UTC by Grarie

2022-11-01 07:00 UTC, mmarx requested changes
Das geht so nicht!

2022-11-03 15:33 UTC, Grarie commented on _includes/next_koma.html
> +        <span class="date">SoSe 2023</span>
Jep. Hab den Link komplett rausgenommen.

2022-11-03 15:35 UTC, Grarie commented
Habe jetzt die geplanten zwei KoMata ohne Link eingefügt.

2022-11-03 16:42 UTC, mmarx approved these changes

2022-11-03 16:42 UTC, merged