Updates beim Kartenspiel
Die-KoMa/die-koma.org pull request #205
Opened 2023-10-04 15:11 UTC by Grarie

Zudem eine temporäre Info bei den Resos entfernt

2023-10-04 15:54 UTC, mmarx requested changes

2023-10-04 15:54 UTC, mmarx commented on publikationen/kartenspiel.md
> +Die Neuauflage des Kartenspielsist eingetroffen!
`Kartenspielsist` ist kein Wort ;)

2023-10-05 14:19 UTC, Grarie commented on publikationen/kartenspiel.md
> +Die Neuauflage des Kartenspielsist eingetroffen!
Done

2023-10-05 14:20 UTC, mmarx approved these changes

2023-10-05 14:20 UTC, merged