Aktuelle Resolinkliste sowie Timeline
Die-KoMa/die-koma.org pull request #211
Opened 2023-11-28 16:13 UTC by Grarie

2023-11-28 16:47 UTC, mmarx requested changes

2023-11-28 16:47 UTC, mmarx commented on ueber_die_koma/timeline.md
> +| SS 2025     | KoMa 91 (KIF 53)         | Uni Passau                   | vsl. Sommer 2025      |
Wenn Magdeburg schon KoMa 91 ist, ist Passau nicht auch KoMa 91.

2023-11-28 16:47 UTC, mmarx commented on publikationen/resolutionen/index.md
> +[**ZaPF: Resolution zum Deutschlandticket**]()
Hier fehlen noch ein Link und ggf. ein Archivlink.

2023-11-28 18:06 UTC, Grarie commented on publikationen/resolutionen/index.md
> +[**ZaPF: Resolution zum Deutschlandticket**]()
Ja, den gibt es noch nicht. Ich versuche gerade ihn zu bekommen, aber existiert leider nicht einmal auf der ZaPF Seite.

2023-11-29 14:54 UTC, mmarx approved these changes

2023-11-29 14:54 UTC, merged