Kleine Änderung an der WSL Anleitung
Die-KoMa/die-koma.org pull request #254
Opened 2024-06-18 11:32 UTC by Grarie

Insbesondere ist die Installation von npm nun optional. Bei Ubuntu noble führt das sonst zu Konflikten, weil npm als Teil von nodejs installiert wird.

2024-06-18 11:39 UTC, mmarx requested changes
Habe das jetzt nicht getestet, aber `nodejs` enthaelt auch unter Ubuntu kein `npm`, das ist ein separates Paket.

2024-06-18 11:39 UTC, mmarx commented on README.md
> +# sudo apt install npm
[x] [doubt](https://packages.ubuntu.com/noble/amd64/nodejs/filelist)
“[nodejs](https://packages.ubuntu.com/noble/nodejs) suggests [npm](https://packages.ubuntu.com/noble/npm)”

2024-06-18 13:27 UTC, Grarie commented on README.md
> +# sudo apt install npm
Stimmt, du hast Recht. Das passiert tatsächlich nur, wenn man für eine neuere Version von nodejs ein Repo via https://deb.nodesource.com/ hinzugefügt hat. Ubuntu noble hat nodejs 18 aber direkt drin und kann beides installieren.

Meinst du, die Trennung der Anleitung wäre ansonsten trotzdem hilfreich?

2024-06-18 13:32 UTC, mmarx commented on README.md
> +# sudo apt install npm
Ich wuerde es bei dem alten Kommando lassen, aber ein Kommentar, dass das ggf. anders funktioniert, wenn du Drittquellen wie `nodesource` benutzt, kann nicht schaden.

2024-06-22 12:36 UTC, Grarie commented on README.md
> +# sudo apt install npm
Ne, lieber nicht zu viel Verwirrung stiften. Aktuell (in noble) ist node ja auch aktuell genug, dass es keine Probleme macht.

Meine Frage bezog sich aber eigentlich darauf, ob ich die Trennung in "einmal auszuführen" und "jedes mal auszuführen" trotzdem einfügen will. Ich bau es mal kurz.

2024-06-22 13:48 UTC, mmarx approved these changes

2024-06-22 13:48 UTC, merged